// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qybwuzdqidrclprvoagv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5Ynd1emRxaWRyY2xwcnZvYWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjM2MzEsImV4cCI6MjA2NDQ5OTYzMX0._9PmRKuQGSLKmbPLMzHgm462wgQomPF7919AXf6X5EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);